import { Injectable } from '@angular/core';
import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Magick } from './magick/magick';
import { Condition } from './magick-conditions/magick-conditions'
import { MagickAdvanced } from './magick-advanced/magick-advanced';

@Injectable({
  providedIn: 'root',
})
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const magicks = [
      { type: 'Fuego',  name: 'Fire',  level: 1, additional: 'Puede causar quemadura', description: '' },
      { type: 'Fuego',  name: 'Fira',  level: 2, additional: 'Puede causar quemadura', description: '' },
      { type: 'Fuego',  name: 'Firaga',  level: 3, additional: 'Puede causar quemadura', description: '' },
      { type: 'Fuego',  name: 'Firaja',  level: 4, additional: 'Puede causar quemadura', description: '' },
      { type: 'Fuego',  name: 'Firaza',  level: 5, additional: 'Puede causar quemadura', description: '' },
      { type: 'Fuego',  name: 'Flare',  level: 6, additional: 'Puede causar quemadura', description: '' },
      { type: 'Fuego',  name: 'Flarega',  level: 7, additional: 'Puede causar quemadura', description: '' },
      { type: 'Agua', name: 'Water',  level: 1, additional: 'Puede causar confusion', description: '' },
      { type: 'Agua', name: 'Watera',  level: 2, additional: 'Puede causar confusion', description: '' },
      { type: 'Agua', name: 'Waterga',  level: 3, additional: 'Puede causar confusion', description: '' },
      { type: 'Agua', name: 'Waterja',  level: 4, additional: 'Puede causar confusion', description: '' },
      { type: 'Agua', name: 'Waterza',  level: 5, additional: 'Puede causar confusion', description: '' },
      { type: 'Agua', name: 'Flood',  level: 6, additional: 'Puede causar confusion', description: '' },
      { type: 'Agua', name: 'Floodga',  level: 7, additional: 'Puede causar confusion', description: '' },
      { type: 'Tierra', name: 'Quake',  level: 1, additional: 'Puede causar aturdir', description: '' },
      { type: 'Tierra', name: 'Quakera',  level: 2, additional: 'Puede causar aturdir', description: '' },
      { type: 'Tierra', name: 'Quakega',  level: 3, additional: 'Puede causar aturdir', description: '' },
      { type: 'Tierra', name: 'Quakeja',  level: 4, additional: 'Puede causar aturdir', description: '' },
      { type: 'Tierra', name: 'Quakeza',  level: 5, additional: 'Puede causar aturdir', description: '' },
      { type: 'Tierra', name: 'Break',  level: 6, additional: 'Puede causar aturdir', description: '' },
      { type: 'Tierra', name: 'Breakga',  level: 7, additional: 'Puede causar aturdir', description: '' },
      { type: 'Viento', name: 'Aero',  level: 1, additional: 'Puede causar confusion', description: '' },
      { type: 'Viento', name: 'Aerora',  level: 2, additional: 'Puede causar confusion', description: '' },
      { type: 'Viento', name: 'Aeroga',  level: 3, additional: 'Puede causar confusion', description: '' },
      { type: 'Viento', name: 'Aeroja',  level: 4, additional: 'Puede causar confusion', description: '' },
      { type: 'Viento', name: 'Aeroza',  level: 5, additional: 'Puede causar confusion', description: '' },
      { type: 'Viento', name: 'Tornado',  level: 6, additional: 'Puede causar confusion', description: '' },
      { type: 'Viento', name: 'Typhoon',  level: 7, additional: 'Puede causar confusion', description: '' },
      { type: 'Electricidad', name: 'Thunder',  level: 1, additional: 'Puede causar paralisis', description: '' },
      { type: 'Electricidad', name: 'Thundara',  level: 2, additional: 'Puede causar paralisis', description: '' },
      { type: 'Electricidad', name: 'Thundaga',  level: 3, additional: 'Puede causar paralisis', description: '' },
      { type: 'Electricidad', name: 'Thundaja',  level: 4, additional: 'Puede causar paralisis', description: '' },
      { type: 'Electricidad', name: 'Thundaza',  level: 5, additional: 'Puede causar paralisis', description: '' },
      { type: 'Electricidad', name: 'Bolt',  level: 6, additional: 'Puede causar paralisis', description: '' },
      { type: 'Electricidad', name: 'Boltga',  level: 7, additional: 'Puede causar paralisis', description: '' },
      { type: 'Hielo',  name: 'Blizzard',  level: 1, additional: 'Puede causar congelamiento', description: '' },
      { type: 'Hielo',  name: 'Blizzara',  level: 2, additional: 'Puede causar congelamiento', description: '' },
      { type: 'Hielo',  name: 'Blizzaga',  level: 3, additional: 'Puede causar congelamiento', description: '' },
      { type: 'Hielo',  name: 'Blizzaja',  level: 4, additional: 'Puede causar congelamiento', description: '' },
      { type: 'Hielo',  name: 'Blizzaza',  level: 5, additional: 'Puede causar congelamiento', description: '' },
      { type: 'Hielo',  name: 'Freeze',  level: 6, additional: 'Puede causar congelamiento', description: '' },
      { type: 'Hielo',  name: 'Freezega',  level: 7, additional: 'Puede causar congelamiento', description: '' },
      { type: 'Natual', name: 'Vine',  level: 1, additional: 'Puede causar envenenamiento',  description: '' },
      { type: 'Natual', name: 'Vinera',  level: 2, additional: 'Puede causar envenenamiento',  description: '' },
      { type: 'Natual', name: 'Vinega',  level: 3, additional: 'Puede causar envenenamiento',  description: '' },
      { type: 'Natual', name: 'Vineja',  level: 4, additional: 'Puede causar envenenamiento',  description: '' },
      { type: 'Natual', name: 'Vineza',  level: 5, additional: 'Puede causar envenenamiento',  description: '' },
      { type: 'Natual', name: 'Forest',  level: 6, additional: 'Puede causar envenenamiento',  description: '' },
      { type: 'Natual', name: 'Forestga',  level: 7, additional: 'Puede causar envenenamiento',  description: '' },
      { type: 'No Elemental', name: 'Shock',  level:1, additional: 'Puede causar aturdir', description: '' },
      { type: 'No Elemental', name: 'Shockra',  level:2, additional: 'Puede causar aturdir', description: '' },
      { type: 'No Elemental', name: 'Shockga',  level:3, additional: 'Puede causar aturdir', description: '' },
      { type: 'No Elemental', name: 'Shockja',  level:4, additional: 'Puede causar aturdir', description: '' },
      { type: 'No Elemental', name: 'Shockza',  level:5, additional: 'Puede causar aturdir', description: '' },
      { type: 'No Elemental', name: 'Pulse',  level:6, additional: 'Puede causar aturdir', description: '' },
      { type: 'No Elemental', name: 'Pulsega',  level:7, additional: 'Puede causar aturdir', description: '' }
    ];

    const advancedMagicks = [
      { type: 'Luz',  name: 'Sacro',  uses: 1,  level: 1, range: '1 objetivo',  effect: '1d10 + 20',  requires: 'Magick 1 - 2' },
      { type: 'Luz',  name: 'Bliss',  uses: 1,  level: 2, range: '3 m2',  effect: '4d12 + 40',  requires: 'Magick 3 - 4' },
      { type: 'Luz',  name: 'Holy', uses: 1,  level: 3, range: '5 m2',  effect: '10d12 + 100',  requires: 'Magick 5 - 6' },
      { type: 'Luz',  name: 'Holyga', uses: 2,  level: 4, range: '10 m2', effect: '(6d12 + 100) * 4', requires: 'Magick 7 - 9' },
      { type: 'Luz',  name: 'Judgement',  uses: 2,  level: 5, range: '15 m2', effect: '(3d12 + 40) * 12 + 1200',  requires: 'Magick 10 - 12' },
      { type: 'Oscuridad',  name: 'Nicto',  uses: 1,  level: 1, range: '1 objetivo',  effect: '1d10 + 20',  requires: 'Magick 1 - 2' },
      { type: 'Oscuridad',  name: 'Ruin', uses: 1,  level: 2, range: '3 m2',  effect: '4d12 + 40',  requires: 'Magick 3 - 4' },
      { type: 'Oscuridad',  name: 'Umbra',  uses: 1,  level: 3, range: '5 m2',  effect: '10d12 + 100',  requires: 'Magick 5 - 6' },
      { type: 'Oscuridad',  name: 'Umbraga',  uses: 2,  level: 4, range: '10 m2', effect: '(6d12 + 100) * 4', requires: 'Magick 7 - 9' },
      { type: 'Oscuridad',  name: 'Doomsday', uses: 2,  level: 5, range: '15 m2', effect: '(3d12 + 40) * 12 + 1200',  requires: 'Magick 10 - 12' },
      { type: 'Gravedad', name: 'Demi', uses: 1,  level: 1, range: '1 objetivo',  effect: 'TBD',  requires: 'Magick 1 - 2' },
      { type: 'Gravedad', name: 'Demira', uses: 1,  level: 2, range: '3 m2',  effect: 'TBD',  requires: 'Magick 3 - 4' },
      { type: 'Gravedad', name: 'Demiga', uses: 1,  level: 3, range: '5 m2',  effect: 'TBD',  requires: 'Magick 5 - 6' },
      { type: 'Gravedad', name: 'Demiza', uses: 2,  level: 4, range: '10 m2', effect: 'TBD', requires: 'Magick 7 - 9' },
      { type: 'Gravedad', name: 'Demija', uses: 2,  level: 5, range: '15 m2', effect: 'TBD',  requires: 'Magick 10 - 12' },
      { type: 'Curacion', name: 'Cure', uses: 1,  level: 1, range: '1 objetivo', effect: 'Heal 1d6 + 20',  requires: 'Magick 1 - 2' },
      { type: 'Curacion', name: 'Cura', uses: 2,  level: 2, range: '1 objetivo', effect: 'Heal 2d8 + 40',  requires: 'Magick 3 - 4' },
      { type: 'Curacion', name: 'Curaga', uses: 3,  level: 3, range: '1 objetivo', effect: 'Heal 4d10 + 80',  requires: 'Magick 5 - 6' },
      { type: 'Curacion', name: 'Regen', uses: 1,  level: 4, range: '1 objetivo', effect: 'Heal 1d12 + 10 x turno',  requires: 'Magick 7 - 9' },
      { type: 'Curacion', name: 'Regenga', uses: 3,  level: 5, range: 'Aliados', effect: 'Heal 2d12 + 20 x turno',  requires: 'Magick 10 - 12' },
      { type: 'Curacion', name: 'Life', uses: 2,  level: 6, range: '1 objetivo', effect: 'Revive al 50% del HP maximo',  requires: 'Magick 13 - 16' },
      { type: 'Curacion', name: 'Full-Life', uses: 4,  level: 7, range: '1 objetivo', effect: 'Revive al 100% del HP maximo',  requires: 'Magick 17 - 20' },
      { type: 'Aumento', name: 'Protect', uses: 1,  level: 1, range: '1 objetivo', effect: 'Reduce el daño fisico a la mitad',  requires: 'Magick 1 - 2' },
      { type: 'Aumento', name: 'Shell', uses: 1,  level: 2, range: '1 objetivo', effect: 'Reduce el daño magico a la mitad',  requires: 'Magick 3 - 4' },
      { type: 'Aumento', name: 'Protectga', uses: 2,  level: 3, range: 'Aliados', effect: 'Reduce el daño fisico a la mitad',  requires: 'Magick 5 - 6' },
      { type: 'Aumento', name: 'Shellga', uses: 2,  level: 4, range: 'Aliados', effect: 'Reduce el daño magico a la mitad',  requires: 'Magick 7 - 9' },
      { type: 'Aumento', name: 'Wall', uses: 3,  level: 5, range: '1 objetivo', effect: 'Reduce todo el daño recibido a la mitad, 100% bloquea proyectiles (flechas, energia, balas)',  requires: 'Magick 10 - 12' },
      { type: 'Aumento', name: 'Wallga', uses: 3,  level: 6, range: 'Aliados', effect: 'Reduce todo el daño recibido a la mitad, 100% bloquea proyectiles (flechas, energia, balas)',  requires: 'Magick 13 - 20' },
      { type: 'Estados', name: 'Blind', uses: 1,  level: 1, range: '1 objetivo', effect: 'Causa ceguera',  requires: 'Magick 1 - 2' },
      { type: 'Estados', name: 'Silence', uses: 1,  level: 2, range: '1 objetivo', effect: 'Causa silencio',  requires: 'Magick 3 - 4' },
      { type: 'Estados', name: 'Sleep', uses: 1,  level: 3, range: '1 objetivo', effect: 'Causa somnolencia',  requires: 'Magick 5 - 6' },
      { type: 'Estados', name: 'Confuse', uses: 1,  level: 4, range: '1 objetivo', effect: 'Causa confusion',  requires: 'Magick 7 - 9' },
      { type: 'Estados', name: 'DeBrave', uses: 1,  level: 5, range: '1 objetivo', effect: 'Reduce el ATQ a la mitad',  requires: 'Magick 10 - 12' },
      { type: 'Estados', name: 'DeFaith', uses: 1,  level: 6, range: '1 objetivo', effect: 'Reduce el Magick a la mitad',  requires: 'Magick 13 - 16' },
      { type: 'Estados', name: 'Peril', uses: 2,  level: 7, range: '1 objetivo', effect: 'Provoca desmayo y reduce el HP a 1 en [Nivel] turnos',  requires: 'Magick 17 - 20' },
      { type: 'Obstruccion', name: 'Provoke', uses: 1,  level: 1, range: 'Usuario', effect: 'Hace que los enemigos solo ataquen al usuario',  requires: 'Magick 1 - 2' },
      { type: 'Obstruccion', name: 'Weak', uses: 1,  level: 2, range: '1 objetivo', effect: 'Provoca fatiga, reduce resistencias elementales',  requires: 'Magick 3 - 4' },
      { type: 'Obstruccion', name: 'Pain', uses: 2,  level: 3, range: '1 objetivo', effect: '3d12 + 60, y envenena, ciega y silencia',  requires: 'Magick 5 - 6' },
      { type: 'Obstruccion', name: 'Curse', uses: 3,  level: 4, range: '1 objetivo', effect: '6d12 + 120, causa fatiga y reduce ATQ y DEF a la mitad',  requires: 'Magick 7 - 9' },
      { type: 'Obstruccion', name: 'Null', uses: 3,  level: 5, range: 'Usuario', effect: 'Niega los efectos de cualquier magia que este afentando al usuario',  requires: 'Magic k 10 - 12' },
      { type: 'Obstruccion', name: 'Death', uses: 4,  level: 6, range: '1 objetivo', effect: 'Probabilidad de eliminar instantaneamente',  requires: 'Magick 13 - 20' },
      { type: 'Veneno', name: 'Venom', uses: 1,  level: 1, range: '1 objetivo', effect: 'Envenena a un enemigo',  requires: 'Magick 1 - 2' },
      { type: 'Veneno', name: 'Bio', uses: 1,  level: 2, range: '1 objetivo', effect: '1d10 + 20 y 20% de probabilidad de envenenar',  requires: 'Magick 3 - 4' },
      { type: 'Veneno', name: 'Biora', uses: 2,  level: 3, range: '1 objetivo', effect: '2d10 + 40 y 30% de probabilidad de envenenar',  requires: 'Magick 5 - 6' },
      { type: 'Veneno', name: 'Bioga', uses: 3,  level: 4, range: '1 objetivo', effect: '4d10 + 60 y 50% de probabilidad de envenenar',  requires: 'Magick 7 - 9' },
      { type: 'Veneno', name: 'Corrosion', uses: 3,  level: 5, range: '1 objetivo', effect: '5d12 + 200 y 80% de probabilidad de envenenar',  requires: 'Magic k 10 - 12' },
      { type: 'Veneno', name: 'Meltdown', uses: 4,  level: 6, range: '1 objetivo', effect: '5d12 + 400 y 70% de probabilidad de inflingir veneno, debilidad y fatiga',  requires: 'Magick 13 - 20' },
      { type: 'Fortaleza', name: 'Brave', uses: 1,  level: 1, range: '1 objetivo', effect: 'Duplica el ATQ',  requires: 'Magick 1 - 2' },
      { type: 'Fortaleza', name: 'Faith', uses: 1,  level: 2, range: '1 objetivo', effect: 'Duplica el Magick',  requires: 'Magick 3 - 4' },
      { type: 'Fortaleza', name: 'Bravera', uses: 2,  level: 3, range: '2 objetivos', effect: 'Duplica el ATQ',  requires: 'Magick 5 - 6' },
      { type: 'Fortaleza', name: 'Faithra', uses: 2,  level: 4, range: '2 objetivos', effect: 'Duplica el Magick',  requires: 'Magick 7 - 9' },
      { type: 'Fortaleza', name: 'Hero', uses: 3,  level: 5, range: '1 objetivo', effect: 'Da inmunidad a todo por 2 turnos',  requires: 'Magic k 10 - 12' },
      { type: 'Fortaleza', name: 'Herora', uses: 4,  level: 6, range: '2 objetivos', effect: 'Da inmunidad a todo por 2 turnos',  requires: 'Magick 13 - 20' },
      { type: 'Tiempo', name: 'Haste', uses: 1,  level: 1, range: '1 objetivo', effect: 'Duplica el numero de acciones por turno',  requires: 'Magick 1 - 2' },
      { type: 'Tiempo', name: 'Slow', uses: 1,  level: 2, range: '1 objetivo', effect: 'Reduce a la mitad el numero de acciones por turno',  requires: 'Magick 3 - 4' },
      { type: 'Tiempo', name: 'Hastega', uses: 2,  level: 3, range: 'Aliados', effect: 'Duplica el numero de acciones por turno',  requires: 'Magick 5 - 6' },
      { type: 'Tiempo', name: 'Slowga', uses: 2,  level: 4, range: 'Rango de vision', effect: 'Reduce a la mitad el numero de acciones por turno',  requires: 'Magick 7 - 9' },
      { type: 'Tiempo', name: 'Stop', uses: 3,  level: 5, range: 'Aliados', effect: 'Evita que se tomen acciones por 3 turnos',  requires: 'Magick 10 - 12' },
      { type: 'Tiempo', name: 'Stopga', uses: 4,  level: 6, range: 'Rango de vision', effect: 'Evita que se tomen acciones por 3 turnos',  requires: 'Magick 13 - 16' },
      { type: 'Tiempo', name: 'Return', uses: 5,  level: 7, range: '1 objetivo', effect: 'Niega todo lo que haya afectado al objetivo en el ultimo turno y lo regresa a su estado anterior',  requires: 'Magick 17 - 20' }
    ];
    
    const conditions = [
      { name: 'Quemadura',  description: 'Reduce el ATQ a la mitad y daña cada turno 5% del HP total'},
      { name: 'Confusion',  description: 'Ataca al azar a un miembro de su equipo'},
      { name: 'Aturdimiento', description: 'Pierde el siguiente turno'},
      { name: 'Paralisis',  description: 'Reduce VEL a la mita,con probabilidad de no tomar acciones en su turno'},
      { name: 'Congelamiento',  description: 'Reduce VEL a 0 y daña cada turno 5% del HP total'},
      { name: 'Envenenamiento', description: 'Daña cada turno 10% del HP total'},
      { name: 'Lentitud', description: 'Reduce a la mitad el numero de turnos que puede tomar'},
      { name: 'Ceguera',  description: 'Requiere 18+ para poder pegar,cancela criticos'},
      { name: 'Silencio', description: 'Imposibilita el uso de reliquias'},
      { name: 'Sangrado', description: 'Reduce el ATQ en un 25% y daña cada turno 5% del HP total'},
      { name: 'Somnolencia',  description: 'Incrementa el daño recibido en 1.5x. Los ataques fisicos terminan el efecto'},
      { name: 'Petrificacion',  description: 'Imposibilita tomar acciones,si no se cura antes de [Nivel] turnos,provoca la muerte al romperse (golpe critico)'},
      { name: 'Debilidad',  description: 'Reduce resistencias elementales'},
      { name: 'Penetrante', description: 'Ignora DEF en el calculo de daño'}
    ];
    return {magicks, advancedMagicks, conditions};
  }
}